# Generated by Django 4.2.2 on 2023-06-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('engineoil', 'Engine-Oil')], default='', max_length=10),
        ),
    ]
