# Generated by Django 4.2.2 on 2023-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('cancel', 'Cancel'), ('packed', 'Packed'), ('on the way', 'On The Way')], default='ending', max_length=50),
        ),
    ]
