# Generated by Django 4.2.2 on 2023-06-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('packed', 'Packed'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancel', 'Cancel'), ('accepted', 'Accepted'), ('on the way', 'On The Way')], default='pending', max_length=50),
        ),
    ]
