# Generated by Django 4.2.2 on 2023-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('on the way', 'On The Way'), ('accepted', 'Accepted'), ('cancel', 'Cancel'), ('delivered', 'Delivered'), ('pending', 'Pending'), ('packed', 'Packed')], default='pending', max_length=50),
        ),
    ]
