# Generated by Django 4.2.2 on 2023-06-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_contact_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('accepted', 'Accepted'), ('on the way', 'On The Way'), ('packed', 'Packed'), ('pending', 'Pending'), ('cancel', 'Cancel')], default='pending', max_length=50),
        ),
    ]
