# Generated by Django 4.2.2 on 2023-06-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('packed', 'Packed'), ('delivered', 'Delivered'), ('on the way', 'On The Way'), ('cancel', 'Cancel'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=50),
        ),
    ]
