# Generated by Django 4.2.2 on 2023-06-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_stock_quantity_alter_orderplaced_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='out_of_stock',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('packed', 'Packed'), ('on the way', 'On The Way'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
